---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekin-shop-frontend
  labels:
    app: ekin-shop
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ekin-shop
      component: frontend
  template:
    metadata:
      labels:
        app: ekin-shop
        component: frontend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ekin-shop-frontend
          image: ekinshop.azurecr.io/frontend:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: API_URL
            - name: BLOB_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: BLOB_URL
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"