apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: ekin-shop
    component: api-service
spec:
  type: LoadBalancer
  selector:
    app: ekin-shop
    component: api
  ports:
  - port: 8080
    targetPort: 8080