apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: ekin-shop
    component: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: ekin-shop
    component: frontend
  ports:
  - port: 80
    targetPort: 3000